### ISSUE TITLE
Replace '@@INSTALLDIR@@' with the installation directory

### ISSUE THREAD

**Issue by samerafach** [osrf/opensplice#16]
In your installation instructions, you ask the user to "replace" that part of the script with the correct directory in the "release.com".

While I like your library so much, I'm really surprised for having to replace that part of the environment variables file myself. In bash, you can get the "directory of the script you're calling" in many ways, one of which is:

    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    OSPL_HOME="${DIR}"

Which I got from stackoverflow. All this, apart from the fact that designing an installer with bash (or some 3rd party scripting language like Python) doesn't take more than one day of work.

The current way is very unintuitive and has cost me a very long time of digging to understand things that should be automated. Please fix these issues. 

Thank you for the great library. I really like it.

**Comment by dirk-thomas** [comment]
Can you please point to the installation instructions you are referring to. If you refer to [this file](https://github.com/osrf/opensplice/blob/master/install/INSTALL.txt) it is provided by OpenSplice itself and not by our fork. Therefore you might create a ticket against the upstream repo instead since we will likely not modify this part in our fork.

The snippet you copied only works in `.bash` files but not in `.sh` files. I assume the instructions use a plain `.sh` file in order to work in various shells and is not specific to `bash`.

**Comment by samerafach** [comment]
Yes. That's the file I'm talking about. I thought you're a part of PrismTech in some way.

Actually even if that doesn't work with sh, I don't find it good practice. There's always a solution better than creating a directory, extracting something in it, and then manually modifying stuff inside it.

Cheers, and thanks for the good work.
